### ISSUE TITLE
User story (to-do): Delete button

### ISSUE THREAD

**Issue by MajaK02** [GavJam80/Project-1#28]
As a user, I want to delete tasks from my list:

- [ ] Each task should have a delete button or icon
- [ ] When I click the delete button, the task should be removed from the list
- [ ] There should be a confirmation prompt before deleting to prevent accidental removals
