### ISSUE TITLE
User story (to-do): Edit button for existing to-do

### ISSUE THREAD

**Issue by MajaK02** [GavJam80/Project-1#30]
As a user, I want to edit existing tasks:

- [ ] Each task should have an edit button or icon
- [ ] When I click the edit button, the task text should become editable
- [ ] There should be a save button to confirm changes
- [ ] If I decide not to edit, there should be a cancel option to revert changes
